version: '3.9'

services:
  test1:
    image: nginx
    networks:
      - my_network
    restart: unless-stopped

  test2:
    image: nginx
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
